// Central source of truth for all SEO data

export const SITE_URL = "https://craftly-studio.vercel.app";
export const SITE_NAME = "Craftly Studio";
export const SITE_TAGLINE = "Digital Experiences Crafted for Business";

export const BUSINESS_INFO = {
  name: "Craftly Studio",
  legalName: "Craftly Studio",
  description:
    "Craftly Studio is a web development and digital solutions agency based in Vapi, Gujarat, India. We design and develop custom websites, web applications, and AI-powered solutions for manufacturing companies, clinics, restaurants, hotels, real estate agencies, and local businesses.",
  shortDescription:
    "We design and develop custom websites that help businesses build trust, attract customers, and grow online.",
  email: "craftly.studio.vapi@gmail.com",
  phone: "" as string,
  foundingYear: 2024,
  address: {
    streetAddress: "Vapi",
    addressLocality: "Vapi",
    addressRegion: "Gujarat",
    postalCode: "396191",
    addressCountry: "IN",
  },
  geo: {
    latitude: 20.3714,
    longitude: 72.9005,
  },
  openingHours: "Mo-Sa 09:00-18:00",
  socialLinks: {
    linkedin: "https://linkedin.com/company/craftlystudio",
    instagram: "https://instagram.com/craftlystudio",
    twitter: "https://twitter.com/craftlystudio",
    facebook: "https://facebook.com/craftlystudio",
  },
  priceRange: "$$",
} as const;

export const NEARBY_LOCATIONS = [
  "Vapi",
  "Daman",
  "Silvassa",
  "Valsad",
  "Umbergaon",
  "Pardi",
  "Bhilad",
  "Dadra and Nagar Haveli",
  "Navsari",
  "Surat",
] as const;

export interface ServiceData {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  keywords: string[];
}

export const SERVICES: ServiceData[] = [
  {
    id: "website-development",
    name: "Website Development",
    slug: "website-development",
    shortDescription:
      "High-performance, SEO-friendly websites built with React and Next.js for businesses in Vapi and Gujarat.",
    metaTitle: "Website Development Services in Vapi, Gujarat",
    metaDescription:
      "Professional website development services in Vapi, Gujarat. Custom React & Next.js websites for manufacturing, healthcare, and local businesses. Fast, SEO-friendly & mobile-first.",
    h1: "Website Development Services in Vapi, Gujarat",
    keywords: [
      "website development Vapi",
      "web development company Vapi",
      "website design company Vapi",
      "website design company in Vapi",
      "website company Vapi",
      "website company near me",
      "website designer Vapi",
      "website development Gujarat",
      "best website development company Vapi",
      "custom website development Vapi",
      "responsive web design Vapi",
      "Next.js website development India",
      "React web development Vapi",
      "modern website design Gujarat",
      "professional web developer Vapi",
      "small business website Vapi",
      "corporate website Vapi GIDC",
      "SEO friendly website design",
      "mobile-first website Vapi",
      "fast loading website developer",
      "one page website Vapi",
      "multi page website Gujarat",
      "custom coded website Vapi",
      "hire website developer near me",
      "affordable website design Vapi",
      "how much does a website cost in Vapi",
      "website development for factories Vapi",
      "web design for clinics Vapi",
    ],
  },
  {
    id: "ecommerce-development",
    name: "E-commerce Development",
    slug: "ecommerce-development",
    shortDescription:
      "Custom e-commerce solutions with secure payments, inventory management, and seamless user experience.",
    metaTitle: "E-commerce Website Development in Vapi, Gujarat",
    metaDescription:
      "Custom e-commerce website development in Vapi. Secure online stores with payment integration, inventory management, and mobile-first design for Gujarat businesses.",
    h1: "E-commerce Website Development in Vapi, Gujarat",
    keywords: [
      "ecommerce development Vapi",
      "ecommerce development company Vapi",
      "ecommerce website company Vapi",
      "online store development Gujarat",
      "ecommerce website Vapi",
      "shopping website development",
      "custom ecommerce solutions",
      "Shopify alternative developer Vapi",
      "WooCommerce developer Gujarat",
      "Next.js ecommerce developer",
      "headless ecommerce Vapi",
      "B2B ecommerce development India",
      "D2C ecommerce website Vapi",
      "product catalog website Vapi",
      "payment gateway integration Razorpay",
      "Stripe integration ecommerce India",
      "inventory management system Vapi",
      "multi-vendor marketplace developer",
      "ecommerce SEO Vapi",
      "abandoned cart recovery setup",
      "ecommerce website for boutique Vapi",
      "online grocery store developer Gujarat",
      "manufacturer B2B store Vapi",
      "hire ecommerce developer Vapi",
      "affordable online store setup Vapi",
      "how to start online store in Gujarat",
    ],
  },
  {
    id: "custom-web-applications",
    name: "Custom Web Applications",
    slug: "custom-web-applications",
    shortDescription:
      "Tailored web applications including CRMs, dashboards, portals, and business management systems.",
    metaTitle: "Custom Web Application Development in Vapi, Gujarat",
    metaDescription:
      "Custom web application development in Vapi, Gujarat. CRM systems, business portals, dashboards & workflow tools built with modern full-stack technologies.",
    h1: "Custom Web Application Development in Vapi, Gujarat",
    keywords: [
      "custom web application Vapi",
      "app development company Vapi",
      "software application development company Vapi",
      "web app development Gujarat",
      "CRM development Vapi",
      "business software development",
      "custom software Vapi",
      "SaaS development company Vapi",
      "internal tools developer India",
      "admin dashboard developer Vapi",
      "customer portal developer Gujarat",
      "vendor portal development Vapi",
      "inventory management app Vapi",
      "booking system developer Gujarat",
      "workflow app developer Vapi",
      "ERP web app Vapi",
      "manufacturing ERP developer India",
      "custom SaaS builder Vapi",
      "multi-tenant web app developer",
      "real-time dashboard Vapi",
      "role-based access web app",
      "Next.js Firebase app developer",
      "hire full stack developer Vapi",
      "affordable custom software Vapi",
      "business process automation Vapi",
      "digitize business workflow Gujarat",
    ],
  },
  {
    id: "seo-services",
    name: "SEO Services",
    slug: "seo-services",
    shortDescription:
      "Technical SEO, local SEO, and content optimization to help your business rank higher on Google and AI search engines.",
    metaTitle: "SEO Company in Vapi | SEO Services & Local SEO Agency",
    metaDescription:
      "The SEO company in Vapi businesses trust. Local SEO, technical SEO & content optimization to help you rank #1 on Google. Get a free SEO audit today.",
    h1: "SEO Company in Vapi, Gujarat",
    keywords: [
      "SEO services Vapi",
      "SEO company Vapi",
      "seo company in vapi",
      "best SEO company in Vapi",
      "SEO agency Vapi",
      "seo company near me",
      "seo services near me",
      "digital marketing company Vapi",
      "top seo companies in Vapi",
      "google ads company Vapi",
      "local seo company Vapi",
      "affordable seo company in Vapi",
      "local SEO Vapi",
      "SEO company Gujarat",
      "Google ranking Vapi",
      "SEO expert Vapi",
      "on-page SEO Vapi",
      "technical SEO agency Vapi",
      "off-page SEO Gujarat",
      "SEO audit Vapi",
      "keyword research service India",
      "backlink building service Vapi",
      "Google My Business optimization Vapi",
      "GMB expert Vapi",
      "local pack ranking Vapi",
      "schema markup implementation",
      "Core Web Vitals optimization Vapi",
      "ecommerce SEO Vapi",
      "SEO for manufacturers Vapi",
      "SEO for clinics Vapi",
      "voice search optimization",
      "AEO answer engine optimization",
      "GEO generative engine optimization",
      "hire SEO consultant Vapi",
      "affordable SEO packages Gujarat",
      "how to rank on Google in Vapi",
    ],
  },
  {
    id: "ai-solutions",
    name: "AI Solutions",
    slug: "ai-solutions",
    shortDescription:
      "AI-powered chatbots, content generation, workflow automation, and intelligent business solutions.",
    metaTitle: "AI Solutions & Integration Services in Vapi, Gujarat",
    metaDescription:
      "AI solutions and integration services in Vapi, Gujarat. Chatbots, AI automation, content generation & intelligent workflows for manufacturing and local businesses.",
    h1: "AI Solutions & Business Automation in Vapi, Gujarat",
    keywords: [
      "AI solutions Vapi",
      "AI automation Gujarat",
      "chatbot development Vapi",
      "AI integration services",
      "business AI solutions",
      "ChatGPT integration developer India",
      "AI chatbot for website Vapi",
      "WhatsApp AI bot Vapi",
      "custom LLM integration Gujarat",
      "OpenAI API developer Vapi",
      "Gemini API integration India",
      "AI content generation service Vapi",
      "AI lead qualification bot Vapi",
      "AI voice assistant developer",
      "RAG chatbot developer India",
      "AI customer support automation",
      "AI-powered search integration",
      "AI image generation website integration",
      "AI email automation Vapi",
      "no-code AI workflow Vapi",
      "hire AI developer Vapi",
      "AI consulting Gujarat",
      "AI for manufacturers Vapi",
      "AI for clinics and hospitals Vapi",
    ],
  },
  {
    id: "business-automation",
    name: "Business Automation",
    slug: "business-automation",
    shortDescription:
      "Streamline operations with custom CRM systems, automated workflows, and process digitization.",
    metaTitle: "Business Automation & CRM Development in Vapi, Gujarat",
    metaDescription:
      "Business automation and CRM development in Vapi. Automate workflows, digitize processes & build custom management systems for manufacturing and service businesses.",
    h1: "Business Automation & CRM Development in Vapi, Gujarat",
    keywords: [
      "business automation Vapi",
      "CRM development Gujarat",
      "workflow automation Vapi",
      "process digitization",
      "manufacturing automation",
      "Zapier alternative developer Vapi",
      "n8n workflow developer India",
      "custom CRM for factories Vapi",
      "lead management system Vapi",
      "sales pipeline software Vapi",
      "invoice automation Gujarat",
      "quotation system developer Vapi",
      "email automation setup Vapi",
      "inventory automation Vapi",
      "purchase order system Gujarat",
      "attendance system web app Vapi",
      "HR management portal Vapi",
      "GST invoicing automation India",
      "digital transformation Vapi",
      "paperless office setup Gujarat",
      "hire automation consultant Vapi",
      "affordable ERP customization Vapi",
      "how to automate my business in Vapi",
      "business process reengineering Gujarat",
    ],
  },
  {
    id: "branding-ui-ux",
    name: "Branding & UI/UX Design",
    slug: "branding-ui-ux",
    shortDescription:
      "Strategic branding and user experience design that builds trust and converts visitors into customers.",
    metaTitle: "Branding Company in Vapi | Branding Services, Logo & Identity",
    metaDescription:
      "The branding company in Vapi for logo design, brand identity & UI/UX. Best branding services Vapi trusts for manufacturers, clinics & local businesses.",
    h1: "Branding Company in Vapi",
    keywords: [
      "branding services Vapi",
      "branding company in Vapi",
      "best branding services Vapi",
      "branding company near me",
      "branding agency Vapi",
      "branding companies in Vapi",
      "branding agency near me",
      "brand identity services Vapi",
      "logo design company Vapi",
      "best branding agency in Vapi",
      "brand design company Vapi",
      "corporate branding company Vapi",
      "rebranding agency Vapi",
      "top branding companies in Vapi",
      "UI UX design Gujarat",
      "logo design Vapi",
      "brand identity design",
      "user experience design Vapi",
      "product design agency Vapi",
      "Figma design Vapi",
      "wireframing service Gujarat",
      "prototyping service India",
      "design system creation Vapi",
      "brand strategy consulting Vapi",
      "visual identity design Gujarat",
      "typography design Vapi",
      "corporate branding Vapi GIDC",
      "startup branding agency India",
      "rebranding services Vapi",
      "packaging design Vapi",
      "social media design Gujarat",
      "brand guidelines document",
      "conversion focused UX design",
      "mobile app UI design Vapi",
      "SaaS UI UX design Vapi",
      "affordable logo design Vapi",
      "hire UI UX designer Gujarat",
    ],
  },
  {
    id: "landing-pages-portfolio",
    name: "Landing Pages & Portfolio Websites",
    slug: "landing-pages-portfolio",
    shortDescription:
      "Conversion-focused landing pages and stunning portfolio websites for professionals and businesses.",
    metaTitle: "Landing Page & Portfolio Website Design in Vapi, Gujarat",
    metaDescription:
      "High-converting landing pages and portfolio websites in Vapi, Gujarat. Perfect for freelancers, agencies, interior designers & professionals. Mobile-first design.",
    h1: "Landing Page & Portfolio Website Design in Vapi, Gujarat",
    keywords: [
      "landing page design Vapi",
      "portfolio website Vapi",
      "single page website Gujarat",
      "conversion-focused landing page",
      "professional portfolio website",
      "high converting landing page Vapi",
      "Framer landing page developer",
      "Next.js landing page India",
      "product launch landing page Vapi",
      "SaaS landing page design",
      "coming soon page Vapi",
      "one page portfolio design Vapi",
      "personal portfolio website India",
      "photographer portfolio site Vapi",
      "designer portfolio website Vapi",
      "architect portfolio site Gujarat",
      "resume website developer India",
      "freelancer portfolio Vapi",
      "startup landing page Gujarat",
      "campaign landing page developer",
      "affordable landing page Vapi",
      "hire portfolio designer Vapi",
      "how to make a portfolio site",
      "landing page vs website difference",
    ],
  },
  {
    id: "software-development",
    name: "Software Development",
    slug: "software-development",
    shortDescription:
      "Custom software development for businesses in Vapi & Gujarat — CRMs, ERPs, portals, and web apps built to streamline your operations.",
    metaTitle: "Software Company in Vapi | Custom Software Development",
    metaDescription:
      "Looking for a software company in Vapi? Craftly Studio builds custom software, CRMs, ERPs & business apps for Vapi GIDC companies. Get a free consultation near you.",
    h1: "Software Company in Vapi, Gujarat",
    keywords: [
      "software company Vapi",
      "software company in Vapi",
      "software company near me",
      "software development company Vapi",
      "custom software development Vapi",
      "software development Vapi",
      "IT company Vapi GIDC",
      "IT company Vapi",
      "IT company in Vapi",
      "it company near me",
      "IT services company Vapi",
      "it services near me",
      "software development near me",
      "software developer company Vapi",
      "custom software company Vapi",
      "best software company in Vapi",
      "software agency Vapi",
      "software consulting Vapi",
      "software development Gujarat",
      "software developer near me",
      "custom software Vapi",
      "business software development",
      "ERP software development Vapi",
      "CRM software company Vapi",
      "custom software development company near me",
      "software development company Gujarat",
      "software engineers Vapi",
      "product development company Vapi",
      "software outsourcing Gujarat",
      "hire software developer Vapi",
      "affordable software company India",
      "software development cost Vapi",
      "enterprise software development Gujarat",
      "software solutions for manufacturers Vapi",
      "software company for small business",
    ],
  },
];

export interface IndustryData {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  keywords: string[];
  relatedServices: string[];
}

export const INDUSTRIES: IndustryData[] = [
  {
    id: "manufacturing",
    name: "Manufacturing & Industrial",
    slug: "manufacturing",
    shortDescription:
      "Digital solutions for manufacturing companies in Vapi industrial area. Product catalogs, B2B portals, and ERP systems.",
    metaTitle: "Website Development for Manufacturing Companies in Vapi",
    metaDescription:
      "Professional website development for manufacturing & industrial companies in Vapi, Gujarat. Product catalogs, B2B portals, ERP integration & digital transformation.",
    h1: "Website Development for Manufacturing Companies in Vapi",
    keywords: [
      "manufacturing website development",
      "industrial website Vapi",
      "factory website design",
      "B2B website development",
      "manufacturing company website",
      "chemical manufacturer website Vapi",
      "pharma manufacturer website Gujarat",
      "textile mill website Vapi",
      "plastic factory website Gujarat",
      "engineering company website Vapi",
      "MSME website design Gujarat",
      "GIDC Vapi factory website",
      "product catalog website manufacturer",
      "B2B inquiry portal Vapi",
      "manufacturer landing page Vapi",
      "exporter website design Gujarat",
      "industrial ecommerce Vapi",
      "ISO certified factory website",
      "OEM website design India",
      "supplier website design Vapi",
      "manufacturing ERP integration website",
      "how to make website for factory",
      "hire developer for manufacturing website",
    ],
    relatedServices: [
      "website-development",
      "custom-web-applications",
      "business-automation",
      "software-development",
    ],
  },
  {
    id: "healthcare-clinics",
    name: "Healthcare & Clinics",
    slug: "healthcare-clinics",
    shortDescription:
      "HIPAA-conscious websites for clinics and hospitals with online appointment booking and patient portals.",
    metaTitle: "Clinic & Hospital Website Development in Vapi, Gujarat",
    metaDescription:
      "Clinic and hospital website development in Vapi. Online appointment booking, patient portals & healthcare websites for doctors, dentists & medical practices in Gujarat.",
    h1: "Clinic & Hospital Website Development in Vapi, Gujarat",
    keywords: [
      "clinic website development",
      "doctor website design",
      "hospital website Vapi",
      "medical website development",
      "online appointment website",
      "dental clinic website Vapi",
      "pediatric clinic website Gujarat",
      "orthopedic doctor website",
      "gynecologist website design Vapi",
      "physiotherapy clinic website",
      "diagnostic center website Vapi",
      "IVF clinic website Gujarat",
      "cosmetic clinic website Vapi",
      "ayurvedic clinic website",
      "homeopathy doctor website India",
      "patient portal developer Vapi",
      "telemedicine website developer",
      "HIPAA aware clinic website",
      "medical practice SEO Vapi",
      "clinic booking system Vapi",
      "hospital appointment system Gujarat",
      "how to make a website for my clinic",
      "hire developer for doctor website",
    ],
    relatedServices: [
      "website-development",
      "custom-web-applications",
      "seo-services",
      "software-development",
    ],
  },
  {
    id: "restaurants-cafes",
    name: "Restaurants & Cafes",
    slug: "restaurants-cafes",
    shortDescription:
      "Appetizing websites for restaurants and cafes with online menus, ordering systems, and table reservations.",
    metaTitle: "Restaurant & Cafe Website Development in Vapi, Gujarat",
    metaDescription:
      "Restaurant and cafe website development in Vapi, Gujarat. Online menus, food ordering systems, table reservations & Google Maps integration for local eateries.",
    h1: "Restaurant & Cafe Website Development in Vapi, Gujarat",
    keywords: [
      "restaurant website design",
      "cafe website development Vapi",
      "online food ordering website",
      "restaurant online menu",
      "food ordering website Gujarat",
      "cloud kitchen website Vapi",
      "bakery website design Vapi",
      "bar and pub website Gujarat",
      "fine dining website design",
      "table reservation system Vapi",
      "QR menu website Vapi",
      "restaurant loyalty program website",
      "food delivery website developer",
      "Zomato alternative website Vapi",
      "Swiggy style ordering website",
      "restaurant Instagram integration",
      "cafe branding and website Vapi",
      "juice bar website Gujarat",
      "ice cream parlor website Vapi",
      "sweet shop website design Gujarat",
      "catering business website Vapi",
      "how to make a restaurant website",
      "hire restaurant web designer Vapi",
    ],
    relatedServices: [
      "website-development",
      "ecommerce-development",
      "seo-services",
    ],
  },
  {
    id: "hotels-resorts",
    name: "Hotels & Resorts",
    slug: "hotels-resorts",
    shortDescription:
      "Premium hospitality websites with booking engines, virtual tours, and revenue management integration.",
    metaTitle: "Hotel & Resort Website Development in Vapi, Gujarat",
    metaDescription:
      "Hotel and resort website development in Vapi, Gujarat. Online booking engines, virtual tours, room showcases & revenue management for hospitality businesses near Daman.",
    h1: "Hotel & Resort Website Development in Vapi, Gujarat",
    keywords: [
      "hotel website development",
      "resort website design Vapi",
      "online hotel booking website",
      "hospitality website development",
      "hotel booking system Gujarat",
      "beach resort website Daman",
      "boutique hotel website design",
      "guest house website Vapi",
      "luxury villa website design",
      "farm stay website Gujarat",
      "hotel PMS integration website",
      "channel manager integration Vapi",
      "hotel virtual tour website",
      "wedding venue website Vapi",
      "banquet hall website Gujarat",
      "resort landing page design",
      "hotel package website builder",
      "spa resort website design India",
      "eco resort website Gujarat",
      "hotel loyalty program website",
      "hire hotel web designer Vapi",
      "how to make a hotel website",
      "affordable hotel website Vapi",
    ],
    relatedServices: [
      "website-development",
      "ecommerce-development",
      "seo-services",
    ],
  },
  {
    id: "real-estate",
    name: "Real Estate & Builders",
    slug: "real-estate",
    shortDescription:
      "Property listing websites for real estate agencies and builders with advanced search and virtual tours.",
    metaTitle: "Real Estate Website Development in Vapi, Gujarat",
    metaDescription:
      "Real estate and builder website development in Vapi, Gujarat. Property listings, advanced search, virtual tours & lead management for realtors and construction companies.",
    h1: "Real Estate Website Development in Vapi, Gujarat",
    keywords: [
      "real estate website development",
      "property listing website Vapi",
      "builder website Gujarat",
      "realtor website development",
      "property management software",
      "real estate portal Vapi",
      "property search website India",
      "MagicBricks alternative developer",
      "99acres style website Vapi",
      "property CRM developer Gujarat",
      "commercial property website Vapi",
      "residential project website Gujarat",
      "villa listing website Vapi",
      "plot sale website Gujarat",
      "rental property website India",
      "real estate lead capture site",
      "3D virtual tour real estate website",
      "brokerage firm website Vapi",
      "township project website Gujarat",
      "affordable real estate website Vapi",
      "hire developer for real estate site",
      "how to make property listing website",
      "SEO for real estate agents Vapi",
    ],
    relatedServices: [
      "website-development",
      "custom-web-applications",
      "seo-services",
      "software-development",
    ],
  },
  {
    id: "education",    name: "Schools & Education",
    slug: "education",
    shortDescription:
      "Modern school, college, and coaching institute websites with LMS, student portals, and parent communication tools.",
    metaTitle: "School & College Website Development in Vapi, Gujarat",
    metaDescription:
      "School, college & coaching institute website development in Vapi, Gujarat. LMS platforms, student portals, admission systems & parent communication tools.",
    h1: "School & College Website Development in Vapi, Gujarat",
    keywords: [
      "school website development",
      "college website Vapi",
      "coaching institute website",
      "LMS development Gujarat",
      "education ERP Vapi",
      "preschool website Vapi",
      "CBSE school website Gujarat",
      "ICSE school website Vapi",
      "university website design India",
      "engineering college website",
      "medical college website Gujarat",
      "coaching classes website Vapi",
      "tuition center website Gujarat",
      "online course platform Vapi",
      "learning management system India",
      "student portal developer Vapi",
      "admission form portal Gujarat",
      "fee payment portal school",
      "parent teacher app developer",
      "school management software Vapi",
      "how to make a school website",
      "affordable school website Vapi",
      "hire developer for coaching institute",
    ],
    relatedServices: [
      "website-development",
      "custom-web-applications",
      "business-automation",
      "software-development",
    ],
  },
  {
    id: "ca-firms",    name: "CA Firms & Accountants",
    slug: "ca-firms",
    shortDescription:
      "Professional websites for chartered accountants and tax consultants with client portals and document management.",
    metaTitle: "CA Firm & Accounting Website Development in Vapi, Gujarat",
    metaDescription:
      "CA firm and accounting practice website development in Vapi, Gujarat. Professional websites with client portals, document management & service showcase for CAs.",
    h1: "CA Firm & Accounting Website Development in Vapi, Gujarat",
    keywords: [
      "CA firm website",
      "chartered accountant website Vapi",
      "tax consultant website",
      "accounting firm website Gujarat",
      "CA website development",
      "GST consultant website Vapi",
      "audit firm website Gujarat",
      "company secretary website Vapi",
      "financial consultant website India",
      "bookkeeping service website",
      "tax filing service website Vapi",
      "ITR filing website Gujarat",
      "CA client portal developer Vapi",
      "document management for CA firm",
      "CA firm SEO Vapi",
      "professional services website Vapi",
      "law firm website Vapi",
      "advocate website design Gujarat",
      "compliance consultant website",
      "how to make a CA firm website",
      "hire developer for CA practice",
      "affordable CA firm website Vapi",
      "modern accounting firm website design",
    ],
    relatedServices: [
      "website-development",
      "seo-services",
      "landing-pages-portfolio",
      "software-development",
    ],
  },
  {
    id: "interior-designers",
    name: "Interior Designers",
    slug: "interior-designers",
    shortDescription:
      "Stunning portfolio websites for interior designers and architects with project galleries and client testimonials.",
    metaTitle: "Interior Designer Portfolio Website in Vapi, Gujarat",
    metaDescription:
      "Interior designer and architect portfolio website development in Vapi, Gujarat. Stunning project galleries, before/after showcases & client testimonial pages.",
    h1: "Interior Designer Portfolio Website in Vapi, Gujarat",
    keywords: [
      "interior designer website",
      "interior design portfolio Vapi",
      "architect website Gujarat",
      "design portfolio website",
      "interior designer website development",
      "modular kitchen designer website",
      "home interior website Vapi",
      "office interior designer website",
      "commercial interior website Gujarat",
      "landscape designer website Vapi",
      "architect firm website India",
      "civil consultant website Vapi",
      "3D visualizer portfolio website",
      "furniture designer website Vapi",
      "lighting designer website Gujarat",
      "before after project gallery site",
      "interior designer SEO Vapi",
      "hire portfolio designer for architect",
      "how to make interior design portfolio",
      "affordable interior designer website",
      "premium architect portfolio Vapi",
      "residential interior website Gujarat",
      "commercial interior portfolio India",
    ],
    relatedServices: [
      "website-development",
      "branding-ui-ux",
      "landing-pages-portfolio",
    ],
  },
];

export const KEYWORDS = {
  // Core money keywords — highest commercial intent for Vapi & Gujarat
  primary: [
    "website development Vapi",
    "web development company Vapi",
    "website designer Vapi",
    "web design company Vapi",
    "website development Gujarat",
    "best website development company Vapi",
    "custom software development Vapi",
    "web design agency Vapi",
    "top web developers Vapi",
    "professional web development Vapi",
    "website development services Vapi",
    "web application development Vapi",
    "software development company Vapi",
    "IT company Vapi",
    "digital agency Vapi Gujarat",
  ],
  // Technology & stack-oriented keywords
  secondary: [
    "digital agency Vapi",
    "web agency Gujarat",
    "full stack development Vapi",
    "React developer Vapi",
    "Next.js development India",
    "responsive website design Vapi",
    "mobile-first web development",
    "front-end developer Vapi",
    "back-end developer Vapi",
    "MERN stack developer Vapi",
    "TypeScript developer India",
    "Node.js developer Vapi",
    "Firebase developer India",
    "Tailwind CSS developer Gujarat",
    "SaaS development company India",
    "PWA development Vapi",
    "headless CMS developer",
    "JAMstack developer India",
    "API development company Vapi",
    "web app developer Gujarat",
    "modern web development Vapi",
    "server-side rendering developer",
    "static site generation developer",
  ],
  // Local + hyperlocal (Vapi & neighboring cities/regions)
  local: [
    "website developer near me",
    "website company near Vapi",
    "best website developer in Vapi",
    "web agency Vapi",
    "Gujarat website development",
    "web design in Vapi Gujarat",
    "Vapi web developer",
    "website development in Vapi GIDC",
    "web design Vapi industrial area",
    "website developer Chala Vapi",
    "web design Chanod Vapi",
    "website developer Silvassa",
    "web designer Daman",
    "web development Valsad",
    "website company Umbergaon",
    "website developer Pardi",
    "web design Surat",
    "web design Navsari",
    "digital agency Bhilad",
    "Dadra Nagar Haveli web developer",
    "website developer south Gujarat",
    "web design agency Union Territories",
    "web development company near Daman",
    "web developer near Silvassa",
    "web design agency near Valsad",
  ],
  // Geo-specific / GEO optimization for map & voice searches
  geo: [
    "web developer Vapi 396191",
    "web design in Gujarat India",
    "GIDC Vapi web design",
    "web development company Chala",
    "digital solutions company Vapi Gujarat",
    "IT services Vapi Gujarat",
    "web design near Silvassa Dadra",
    "website designer near Daman",
    "hire developer in Vapi Gujarat India",
    "web design company south Gujarat",
    "digital agency near me Vapi",
    "Vapi Chanod web development",
    "Union Territory Daman Diu web design",
  ],
  // Commercial buying-intent phrases
  commercial: [
    "hire website developer Vapi",
    "hire web developer Gujarat",
    "affordable website development",
    "professional website design",
    "corporate website development",
    "business website development",
    "cheap website design Vapi",
    "website development cost Vapi",
    "website price in Vapi",
    "hire freelance developer Vapi",
    "outsource web development Gujarat",
    "web development agency price India",
    "custom website quote Vapi",
    "website maintenance services Vapi",
    "monthly website management Vapi",
    "annual website support plans India",
    "get free website quote Vapi",
    "website revamp cost Gujarat",
    "buy website package Vapi",
  ],
  // Service-line specific keywords
  service: [
    "ecommerce website development Vapi",
    "online store development Gujarat",
    "landing page design Vapi",
    "portfolio website design Vapi",
    "SEO services Vapi",
    "local SEO Vapi Gujarat",
    "Google My Business optimization Vapi",
    "on-page SEO expert India",
    "technical SEO agency Vapi",
    "AI chatbot development Vapi",
    "AI automation services Gujarat",
    "workflow automation Vapi",
    "CRM development India",
    "ERP integration Vapi",
    "logo design Vapi",
    "brand identity design Gujarat",
    "UI UX design Vapi",
    "product design agency India",
    "mobile app development Vapi",
    "Progressive Web App development",
    "single page application development",
    "web hosting setup Vapi",
    "domain and hosting Vapi",
    "website speed optimization Gujarat",
    "core web vitals optimization",
    "schema markup services India",
  ],
  // Industry / vertical keywords
  industry: [
    "manufacturing website design Vapi",
    "factory website Gujarat",
    "industrial website developer Vapi GIDC",
    "chemical company website design",
    "pharma company website Vapi",
    "textile company website design",
    "engineering company website Gujarat",
    "clinic website design Vapi",
    "hospital website developer Gujarat",
    "doctor website design India",
    "dental clinic website Vapi",
    "restaurant website design Vapi",
    "cafe website developer Gujarat",
    "hotel website design Vapi Daman",
    "resort website builder Gujarat",
    "real estate website Vapi",
    "builder website design Gujarat",
    "school website developer Vapi",
    "college website design Gujarat",
    "coaching institute website India",
    "CA firm website design Vapi",
    "law firm website developer India",
    "interior designer portfolio website",
    "architect website design Vapi",
    "gym fitness studio website Vapi",
    "salon spa website design",
    "boutique ecommerce store Vapi",
    "NGO nonprofit website design Gujarat",
    "auto dealership website India",
  ],
  // Long-tail (5+ words) — high-conversion niche searches
  longTail: [
    "how to build a website for my business in Vapi",
    "affordable website development company for small business Vapi",
    "custom Next.js website development in Gujarat",
    "SEO optimized website design agency Vapi",
    "mobile responsive website developer Vapi Gujarat",
    "website redesign company in Vapi",
    "professional business website design Gujarat India",
    "e-commerce website for manufacturers in Vapi",
    "AI powered website development India",
    "React Next.js developer for hire in Vapi",
    "best web design agency for factories in GIDC Vapi",
    "modern portfolio website design for architects Vapi",
    "high converting landing page design agency India",
    "website with online booking for clinic in Vapi",
    "restaurant website with menu and online ordering Vapi",
    "custom CRM development for manufacturers Vapi",
    "multi-language website developer Gujarat",
    "b2b website with product catalog developer Vapi",
    "school ERP and website integration Vapi",
    "hotel booking website with payment gateway Gujarat",
  ],
  // Voice search — natural conversational queries
  voice: [
    "who builds websites near me",
    "best website developer near Vapi",
    "website company near me",
    "affordable website designer near me",
    "website developer for factory",
    "website developer for clinic",
    "who is the best web developer in Vapi",
    "which company makes websites in Vapi",
    "how much does a website cost in Gujarat",
    "how long does it take to build a website",
    "where can I hire a web designer near Vapi",
    "top rated digital agency in south Gujarat",
    "who does SEO in Vapi",
    "best CRM developer near me",
    "who builds ecommerce websites in Gujarat",
    "who can redesign my old website",
    "where do I get a website made in Vapi",
    "which agency builds fastest websites",
  ],
  // Answer-Engine Optimization — question-style queries for LLM/AI answers
  aeo: [
    "what is the best web development company in Vapi",
    "how much does website development cost in Vapi",
    "how to choose a web developer in Gujarat",
    "why do I need a website for my business",
    "what does an SEO agency do",
    "how long does it take to build an ecommerce website",
    "difference between website and web application",
    "benefits of custom website over template",
    "what technologies does Craftly Studio use",
    "does Craftly Studio work with small businesses",
    "can Craftly Studio integrate AI in my website",
    "what industries does Craftly Studio serve",
    "is Next.js good for business websites",
    "what makes a website SEO-friendly",
    "how to rank a Vapi business on Google",
    "is a landing page enough for a small business",
    "which is better WordPress or Next.js",
  ],
  // Problem-aware keywords — users searching for a fix
  problem: [
    "my website is slow how to fix",
    "my website is not ranking on Google",
    "outdated website redesign Vapi",
    "website not mobile responsive fix",
    "no leads from my website",
    "website security issues fix Vapi",
    "migrate WordPress to Next.js Vapi",
    "convert PSD Figma to Next.js Vapi",
    "improve website conversion rate Gujarat",
    "reduce website bounce rate India",
    "fix broken website links Vapi",
    "recover website from Google penalty",
    "SSL certificate setup Vapi",
    "website downtime fix service",
  ],
  // Brand keywords — direct name searches
  brand: [
    "Craftly Studio",
    "Craftly Studio Vapi",
    "Craftly Studio Gujarat",
    "craftlystudio",
    "craftly studio agency",
    "Craftly Studio reviews",
    "Craftly Studio portfolio",
    "Craftly Studio contact",
    "Craftly Studio pricing",
    "Craftly Studio careers",
    "Craftly Studio services",
  ],
} as const;
